### ISSUE TITLE
Some question about the servo

### ISSUE THREAD

**Issue by keygoman** [ms-iot/petdoor#8]
I have built the project and deployed successfully.
The question was when the Indoor motion worked and shown “Indoor motion detected”，but the servo didn't work.
![image](https://user-images.githubusercontent.com/39460584/40279869-e4c71ea4-5c7c-11e8-8d8f-79166cbfc27e.png)

The second question was when the Outdoor motion worked but thrown these exception 
![image](https://user-images.githubusercontent.com/39460584/40279996-60c92900-5c7f-11e8-8a17-ce6bb3557f59.png)

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.
